#!/usr/bin/env bash
# pings 5 times an IP address passed as an argument

if [ -z "$IP_ADDRESS" ]; then
    echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
    exit 1
fi

ping -c 5 "$IP_ADDRESS"