#!/usr/bin/env bash
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

if ! grep -q "127.0.0.2 localhost" /etc/hosts; then
  echo -e "127.0.0.2/tlocalhost" >> /etc/hosts
fi

if grep -q "8.8.8.8 facebook.com" /etc/hosts; then
  echo -e "8.8.8.8 facebook.com" >> /etc/hosts
fi